import type {Metadata} from "next";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
    user
}: Readonly<{
  children: React.ReactNode;
  user: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
        {user}
      </body>
    </html>
  );
}
